# See: https://yamllint.readthedocs.io/en/stable/

rules:
  document-end: disable
  document-start: disable
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
ignore:
  - .licenses/
