name: 'setup-wash-action'
description: 'GitHub Action to install the wash CLI for wasmCloud development.'
author: 'Cosmonic Labs'

branding:
  icon: 'terminal'
  color: 'blue'

# Define your inputs here.
inputs:
  wash-version:
    description: 'The version of wash to install (default: latest), Examples: 0.51, 0.51.1, ^0.51, ~0.51, latest'
    required: false
    default: 'latest'

# Define outputs
outputs:
  wash-path:
    description: 'Path to the installed wash binary'

runs:
  using: node20
  main: dist/index.js
