name: 'setup-wash'
description: 'GitHub Action to install the wash CLI for wasmCloud development.'
author: 'Cosmonic Labs'

branding:
  icon: 'terminal'
  color: 'blue'

# Define your inputs here.
inputs:
  version:
    description: 'Version of wash to install (default: latest)'
    required: false
    default: 'latest'

# No outputs for now
outputs: { }

runs:
  using: node20
  main: dist/index.js
