name: 'setup-wash-action'
description: 'GitHub Action to install the wash CLI for wasmCloud development.'
author: 'Cosmonic Labs'

branding:
  icon: 'terminal'
  color: 'blue'

# Define your inputs here.
inputs:
  wash-version:
    description: 'The version of wash to install (default: latest), Examples: 0.51, 0.51.1, ^0.51, ~0.51, latest'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install wash using taiki-e/cache-cargo-install-action
      uses: taiki-e/cache-cargo-install-action@v1
      with:
        tool: wash
        git: 'https://github.com/cosmonic-labs/wash'
        rev: '14a51ee71ec653be4b5ac302a2ce4708d36b83f3'
